CREATE TABLE IF NOT EXISTS UserData(
  ID SERIAL PRIMARY KEY,
  Name VARCHAR(32) NOT NULL,
  Password VARCHAR(32) NOT NULL,
  Email VARCHAR(64) UNIQUE NOT NULL,
  Address VARCHAR(64) NOT NULL,
  PhoneNumber VARCHAR(16) NOT NULL,
  Birthday TIMESTAMP,
  Authority INT NOT NULL
);