INSERT INTO product_label (product_id, label_name, required) VALUES
    (2,'sugar', true),
    (7,'rice', true),
    (8, 'kimchi', false),
    (9, 'kimchi', false),
    (10, 'UE 口味選項', true),
    (11, 'UE 口味選項', true),
    (12, 'UE 口味選項', true),
    (13, 'UE 口味選項', true),
    (14, 'UE 口味選項', true),
    (15, 'UE 口味選項', true),
    (20, '選擇', false),
    (20, '份量選擇', false),
    (21, '選擇', false),
    (21, '份量選擇', false),
    (22, '選擇', false),
    (22, '份量選擇', false),
    (23, '選擇', false),
    (23, '份量選擇', false),
    (23, '餃類選擇', true),
    (24, '選擇', false),
    (24, '份量選擇', false),
    (25, '辣度選擇', true),
    (25, '主食選擇', true),
    (26, '辣度選擇', true),
    (26, '加購', true),
    (27, '辣度選擇', true),
    (27, '乾湯需求', true),
    (28, '辣度選擇', true),
    (28, '主食選擇', true),
    (29, '辣度選擇', true),
    (30, '辣度選擇', true),
    (30, '加購', true),
    (31, '點心選項 Choose Snacks', true),
    (31, '飲品選擇 Choose Beverage', true),
    (31, '點心加購 Add-Ons Snacks', false),
    (32, '點心選項 Choose Snacks', true),
    (32, '飲品選擇 Choose Beverage', true),
    (32, '點心加購 Add-Ons Snacks', false),
    (33, '點心選項 Choose Snacks', true),
    (33, '飲品選擇 Choose Beverage', true),
    (33, '點心加購 Add-Ons Snacks', false),
    (34, '點心選項 Choose Snacks', true),
    (34, '飲品選擇 Choose Beverage', true),
    (34, '點心加購 Add-Ons Snacks', false),
    (42, '份量 / Size', true),
    (42, '飯量 / Adjust the amount of rice', true),
    (42, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (42, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (42, '配料 / Toppings', false),
    (42, '飲料 / Drinks', false),
    (43, '份量 / Size', true),
    (43, '飯量 / Adjust the amount of rice', true),
    (43, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (43, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (43, '配料 / Toppings', false),
    (43, '飲料 / Drinks', false),
    (44, '份量 / Size', true),
    (44, '飯量 / Adjust the amount of rice', true),
    (44, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (44, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (44, '配料 / Toppings', false),
    (44, '飲料 / Drinks', false),
    (45, '份量 / Size', true),
    (45, '飯量 / Adjust the amount of rice', true),
    (45, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (45, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (45, '配料 / Toppings', false),
    (45, '飲料 / Drinks', false),
    (46, '份量 / Size', true),
    (46, '飯量 / Adjust the amount of rice', true),
    (46, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (46, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (46, '配料 / Toppings', false),
    (46, '飲料 / Drinks', false),
    (47, '份量 / Size', true),
    (47, '飯量 / Adjust the amount of rice', true),
    (47, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (47, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (47, '配料 / Toppings', false),
    (47, '飲料 / Drinks', false),
    (48, '份量 / Size', true),
    (48, '飯量 / Adjust the amount of rice', true),
    (48, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (48, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (48, '配料 / Toppings', false),
    (48, '飲料 / Drinks', false),
    (49, '份量 / Size', true),
    (49, '飯量 / Adjust the amount of rice', true),
    (49, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (49, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (49, '配料 / Toppings', false),
    (49, '飲料 / Drinks', false),
    (50, '份量 / Size', true),
    (50, '飯量 / Adjust the amount of rice', true),
    (50, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', false),
    (50, '優惠加購配菜 / Side Order（ $5 OFF!! ）', false),
    (50, '配料 / Toppings', false),
    (50, '飲料 / Drinks', false),
    (62, '份量', false),
    (63, '份量', false),
    (72, '加購選項', false),
    (73, '加購選項', false),
    (74, '加購選項', false),
    (75, '加購選項', false),
    (76, '加購選項', false),
    (77, '加購選項', false),
    (78, '加購選項', false),
    (79, '飯量選擇', true),
    (79, '配料選擇', true),
    (80, '飯量選擇', true),
    (80, '配料選擇', true),
    (81, '飯量選擇', true),
    (81, '配料選擇', true),
    (82, '飯量選擇', true),
    (82, '配料選擇', true),
    (83, '飯量選擇', true),
    (83, '配料選擇', true),
    (84, '甜度選擇 Choose Sweetness Level', true),
    (84, '冰量選擇 Ice Level', true),
    (84, '加料 Add-On', true),
    (85, '甜度選擇 Choose Sweetness Level', true),
    (85, '冰量選擇 Ice Level', true),
    (85, '加料 Add-On', true),
    (86, '甜度選擇 Choose Sweetness Level', true),
    (86, '冰量選擇 Ice Level', true),
    (86, '溫度 Beverage Temperature', true),
    (87, '甜度選擇 Choose Sweetness Level', true),
    (87, '冰量選擇 Ice Level', true),
    (87, '加料 Add-On', true),
    (88, '甜度選擇 Choose Sweetness Level', true),
    (88, '冰量選擇 Ice Level', true),
    (88, '加料 Add-On', true),
    (89, '甜度選擇 Choose Sweetness Level', true),
    (89, '冰量選擇 Ice Level', true),
    (89, '加料 Add-On', true)
    





    