INSERT INTO label_item (product_id, label_name, item_name) VALUES
    (2, 'sugar', 'more'),
    (2, 'sugar', 'less'),
    (2, 'sugar', 'no'),
    (7, 'rice', 'yes'),
    (7, 'rice', 'no'),
    (8, 'kimchi', 'yes'),
    (8, 'kimchi', 'no'),
    (9, 'kimchi', 'yes'),
    (9, 'kimchi', 'no'),
    (10, 'UE 口味選項', 'UE 加手工蔥醬'),
    (10, 'UE 口味選項', 'UE 加手工辣椒醬(小辣)'),
    (10, 'UE 口味選項', 'UE 加手工蔥醬、辣椒醬(小辣)'),
    (10, 'UE 口味選項', '蔥 辣 都 不加'),
    (11, 'UE 口味選項', 'UE 加手工蔥醬'),
    (11, 'UE 口味選項', 'UE 加手工辣椒醬(小辣)'),
    (11, 'UE 口味選項', 'UE 加手工蔥醬、辣椒醬(小辣)'),
    (11, 'UE 口味選項', '蔥 辣 都 不加'),
    (12, 'UE 口味選項', 'UE 加手工蔥醬'),
    (12, 'UE 口味選項', 'UE 加手工辣椒醬(小辣)'),
    (12, 'UE 口味選項', 'UE 加手工蔥醬、辣椒醬(小辣)'),
    (12, 'UE 口味選項', '蔥 辣 都 不加'),
    (13, 'UE 口味選項', 'UE 加手工蔥醬'),
    (13, 'UE 口味選項', 'UE 加手工辣椒醬(小辣)'),
    (13, 'UE 口味選項', 'UE 加手工蔥醬、辣椒醬(小辣)'),
    (13, 'UE 口味選項', '蔥 辣 都 不加'),
    (14, 'UE 口味選項', 'UE 加手工蔥醬'),
    (14, 'UE 口味選項', 'UE 加手工辣椒醬(小辣)'),
    (14, 'UE 口味選項', 'UE 加手工蔥醬、辣椒醬(小辣)'),
    (14, 'UE 口味選項', '蔥 辣 都 不加'),
    (15, 'UE 口味選項', 'UE 加手工蔥醬'),
    (15, 'UE 口味選項', 'UE 加手工辣椒醬(小辣)'),
    (15, 'UE 口味選項', 'UE 加手工蔥醬、辣椒醬(小辣)'),
    (15, 'UE 口味選項', '蔥 辣 都 不加'),
    (20, '選擇', '加辣'),
    (20, '份量選擇', '加大'),
    (21, '選擇', '加辣'),
    (21, '份量選擇', '加大'),
    (22, '選擇', '加辣'),
    (22, '份量選擇', '加大'),
    (23, '選擇', '加辣'),
    (23, '份量選擇', '加大12顆'),
    (23, '餃類選擇', '韭菜'),
    (23, '餃類選擇', '高麗菜'),
    (24, '份量選擇', '加大'),
    (24, '選擇', '加辣'),
    (25, '主食選擇', '飯'),
    (25, '主食選擇', '麵'),
    (25, '辣度選擇', '不辣'),
    (25, '辣度選擇', '微辣'),
    (25, '辣度選擇', '小辣'),
    (25, '辣度選擇', '中辣'),
    (25, '辣度選擇', '大辣'),
    (26, '加購', '加麵'),
    (26, '辣度選擇', '不辣'),
    (26, '辣度選擇', '微辣'),
    (26, '辣度選擇', '小辣'),
    (26, '辣度選擇', '中辣'),
    (26, '辣度選擇', '大辣'),
    (27, '辣度選擇', '不辣'),
    (27, '辣度選擇', '微辣'),
    (27, '辣度選擇', '小辣'),
    (27, '辣度選擇', '中辣'),
    (27, '辣度選擇', '大辣'),
    (27, '乾湯需求', '乾'),
    (27, '乾湯需求', '湯'),
    (28, '主食選擇', '飯'),
    (28, '主食選擇', '麵'),
    (28, '辣度選擇', '不辣'),
    (28, '辣度選擇', '微辣'),
    (28, '辣度選擇', '小辣'),
    (28, '辣度選擇', '中辣'),
    (28, '辣度選擇', '大辣'),
    (29, '辣度選擇', '不辣'),
    (29, '辣度選擇', '微辣'),
    (29, '辣度選擇', '小辣'),
    (29, '辣度選擇', '中辣'),
    (29, '辣度選擇', '大辣'),
    (30, '辣度選擇', '不辣'),
    (30, '辣度選擇', '微辣'),
    (30, '辣度選擇', '小辣'),
    (30, '辣度選擇', '中辣'),
    (30, '辣度選擇', '大辣'),
    (30, '加購', '加麵'),
    (31, '點心選項 Choose Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (31, '點心選項 Choose Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (31, '點心選項 Choose Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (31, '點心選項 Choose Snacks', 'V型薯條【1份】V-Fries'),
    (31, '點心選項 Choose Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (31, '點心選項 Choose Snacks', '薯條 (XL) French Fries (XL)'),
    (31, '飲品選擇 Choose Beverage', '冰紅茶【L｜甜度固定】Iced Black Tea(L)'),
    (31, '飲品選擇 Choose Beverage', '摩斯蒟蒻冰紅茶'),
    (31, '飲品選擇 Choose Beverage', '熱摩斯咖啡 【L】MOS Coffee(Hot)(L)'),
    (31, '飲品選擇 Choose Beverage', '冰摩斯咖啡 【L】MOS Coffee(Iced)(L)'),
    (31, '飲品選擇 Choose Beverage', '熱拿鐵咖啡 【L】Café Latte(Hot)(L)'),
    (31, '飲品選擇 Choose Beverage', '冰拿鐵咖啡 【L】Café Latte(Iced)(L)'),
    (31, '飲品選擇 Choose Beverage', '黃金地瓜冰奶茶【L |冰】Sweet Potato Milk Tea (Iced)(L)'),
    (31, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 熱】Sweet Potato Café Latte (Hot)(M)'),
    (31, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 冰】Sweet Potato Café Latte (Iced)(M)'),
    (31, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【冰】Match Milk Tea(Iced)'),
    (31, '飲品選擇 Choose Beverage', '100%台灣冰綠茶【L|無糖】100% Taiwan Iced Green Tea(Sugar free)(L)'),
    (31, '飲品選擇 Choose Beverage', '冰紅茶【L|無糖】Iced Black Tea(Sugar free)(L)'),
    (31, '飲品選擇 Choose Beverage', '可樂【L】Coke(L)'),
    (31, '飲品選擇 Choose Beverage', '雪碧【L】Sprite(L)'),
    (31, '飲品選擇 Choose Beverage', '摩斯經典奶茶【L│冰】MOS Milk Tea (L) (Iced)'),
    (31, '飲品選擇 Choose Beverage', '柚子冰茶Pomelo Tea(Iced)'),
    (31, '飲品選擇 Choose Beverage', '100%新鮮橘子汁【M|不加冰】100% Orange Juice'),
    (31, '飲品選擇 Choose Beverage', '摩斯熱紅茶Hot Black Tea'),
    (31, '飲品選擇 Choose Beverage', '摩斯玄米煎茶MOS Genmai Green Tea'),
    (31, '飲品選擇 Choose Beverage', '豚汁蔬菜湯 Japanese Pork Soup'),
    (31, '飲品選擇 Choose Beverage', '玉米濃湯【L】Corn Soup (L)'),
    (31, '飲品選擇 Choose Beverage', '熱摩斯奶茶【M】MOS Milk Tea(Hot)'),
    (31, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【熱】Match Milk Tea(Hot)'),
    (31, '點心加購 Add-Ons Snacks', '和風炸雞【1份】Mos Chicken'),
    (31, '點心加購 Add-Ons Snacks', 'MOS 米蕾夢【1 份】MOS Rice Lemon Cake'),
    (31, '點心加購 Add-Ons Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (31, '點心加購 Add-Ons Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (31, '點心加購 Add-Ons Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (31, '點心加購 Add-Ons Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (31, '點心加購 Add-Ons Snacks', '薯條 (XL) French Fries (XL)'),
    (31, '點心加購 Add-Ons Snacks', 'V型薯條【1份】V-Fries'),
    (32, '點心選項 Choose Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (32, '點心選項 Choose Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (32, '點心選項 Choose Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (32, '點心選項 Choose Snacks', 'V型薯條【1份】V-Fries'),
    (32, '點心選項 Choose Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (32, '點心選項 Choose Snacks', '薯條 (XL) French Fries (XL)'),
    (32, '飲品選擇 Choose Beverage', '冰紅茶【L｜甜度固定】Iced Black Tea(L)'),
    (32, '飲品選擇 Choose Beverage', '摩斯蒟蒻冰紅茶'),
    (32, '飲品選擇 Choose Beverage', '熱摩斯咖啡 【L】MOS Coffee(Hot)(L)'),
    (32, '飲品選擇 Choose Beverage', '冰摩斯咖啡 【L】MOS Coffee(Iced)(L)'),
    (32, '飲品選擇 Choose Beverage', '熱拿鐵咖啡 【L】Café Latte(Hot)(L)'),
    (32, '飲品選擇 Choose Beverage', '冰拿鐵咖啡 【L】Café Latte(Iced)(L)'),
    (32, '飲品選擇 Choose Beverage', '黃金地瓜冰奶茶【L |冰】Sweet Potato Milk Tea (Iced)(L)'),
    (32, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 熱】Sweet Potato Café Latte (Hot)(M)'),
    (32, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 冰】Sweet Potato Café Latte (Iced)(M)'),
    (32, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【冰】Match Milk Tea(Iced)'),
    (32, '飲品選擇 Choose Beverage', '100%台灣冰綠茶【L|無糖】100% Taiwan Iced Green Tea(Sugar free)(L)'),
    (32, '飲品選擇 Choose Beverage', '冰紅茶【L|無糖】Iced Black Tea(Sugar free)(L)'),
    (32, '飲品選擇 Choose Beverage', '可樂【L】Coke(L)'),
    (32, '飲品選擇 Choose Beverage', '雪碧【L】Sprite(L)'),
    (32, '飲品選擇 Choose Beverage', '摩斯經典奶茶【L│冰】MOS Milk Tea (L) (Iced)'),
    (32, '飲品選擇 Choose Beverage', '柚子冰茶Pomelo Tea(Iced)'),
    (32, '飲品選擇 Choose Beverage', '100%新鮮橘子汁【M|不加冰】100% Orange Juice'),
    (32, '飲品選擇 Choose Beverage', '摩斯熱紅茶Hot Black Tea'),
    (32, '飲品選擇 Choose Beverage', '摩斯玄米煎茶MOS Genmai Green Tea'),
    (32, '飲品選擇 Choose Beverage', '豚汁蔬菜湯 Japanese Pork Soup'),
    (32, '飲品選擇 Choose Beverage', '玉米濃湯【L】Corn Soup (L)'),
    (32, '飲品選擇 Choose Beverage', '熱摩斯奶茶【M】MOS Milk Tea(Hot)'),
    (32, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【熱】Match Milk Tea(Hot)'),
    (32, '點心加購 Add-Ons Snacks', '和風炸雞【1份】Mos Chicken'),
    (32, '點心加購 Add-Ons Snacks', 'MOS 米蕾夢【1 份】MOS Rice Lemon Cake'),
    (32, '點心加購 Add-Ons Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (32, '點心加購 Add-Ons Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (32, '點心加購 Add-Ons Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (32, '點心加購 Add-Ons Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (32, '點心加購 Add-Ons Snacks', '薯條 (XL) French Fries (XL)'),
    (32, '點心加購 Add-Ons Snacks', 'V型薯條【1份】V-Fries'),
    (33, '點心選項 Choose Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (33, '點心選項 Choose Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (33, '點心選項 Choose Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (33, '點心選項 Choose Snacks', 'V型薯條【1份】V-Fries'),
    (33, '點心選項 Choose Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (33, '點心選項 Choose Snacks', '薯條 (XL) French Fries (XL)'),
    (33, '飲品選擇 Choose Beverage', '冰紅茶【L｜甜度固定】Iced Black Tea(L)'),
    (33, '飲品選擇 Choose Beverage', '摩斯蒟蒻冰紅茶'),
    (33, '飲品選擇 Choose Beverage', '熱摩斯咖啡 【L】MOS Coffee(Hot)(L)'),
    (33, '飲品選擇 Choose Beverage', '冰摩斯咖啡 【L】MOS Coffee(Iced)(L)'),
    (33, '飲品選擇 Choose Beverage', '熱拿鐵咖啡 【L】Café Latte(Hot)(L)'),
    (33, '飲品選擇 Choose Beverage', '冰拿鐵咖啡 【L】Café Latte(Iced)(L)'),
    (33, '飲品選擇 Choose Beverage', '黃金地瓜冰奶茶【L |冰】Sweet Potato Milk Tea (Iced)(L)'),
    (33, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 熱】Sweet Potato Café Latte (Hot)(M)'),
    (33, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 冰】Sweet Potato Café Latte (Iced)(M)'),
    (33, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【冰】Match Milk Tea(Iced)'),
    (33, '飲品選擇 Choose Beverage', '100%台灣冰綠茶【L|無糖】100% Taiwan Iced Green Tea(Sugar free)(L)'),
    (33, '飲品選擇 Choose Beverage', '冰紅茶【L|無糖】Iced Black Tea(Sugar free)(L)'),
    (33, '飲品選擇 Choose Beverage', '可樂【L】Coke(L)'),
    (33, '飲品選擇 Choose Beverage', '雪碧【L】Sprite(L)'),
    (33, '飲品選擇 Choose Beverage', '摩斯經典奶茶【L│冰】MOS Milk Tea (L) (Iced)'),
    (33, '飲品選擇 Choose Beverage', '柚子冰茶Pomelo Tea(Iced)'),
    (33, '飲品選擇 Choose Beverage', '100%新鮮橘子汁【M|不加冰】100% Orange Juice'),
    (33, '飲品選擇 Choose Beverage', '摩斯熱紅茶Hot Black Tea'),
    (33, '飲品選擇 Choose Beverage', '摩斯玄米煎茶MOS Genmai Green Tea'),
    (33, '飲品選擇 Choose Beverage', '豚汁蔬菜湯 Japanese Pork Soup'),
    (33, '飲品選擇 Choose Beverage', '玉米濃湯【L】Corn Soup (L)'),
    (33, '飲品選擇 Choose Beverage', '熱摩斯奶茶【M】MOS Milk Tea(Hot)'),
    (33, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【熱】Match Milk Tea(Hot)'),
    (33, '點心加購 Add-Ons Snacks', '和風炸雞【1份】Mos Chicken'),
    (33, '點心加購 Add-Ons Snacks', 'MOS 米蕾夢【1 份】MOS Rice Lemon Cake'),
    (33, '點心加購 Add-Ons Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (33, '點心加購 Add-Ons Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (33, '點心加購 Add-Ons Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (33, '點心加購 Add-Ons Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (33, '點心加購 Add-Ons Snacks', '薯條 (XL) French Fries (XL)'),
    (33, '點心加購 Add-Ons Snacks', 'V型薯條【1份】V-Fries'),
    (34, '點心選項 Choose Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (34, '點心選項 Choose Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (34, '點心選項 Choose Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (34, '點心選項 Choose Snacks', 'V型薯條【1份】V-Fries'),
    (34, '點心選項 Choose Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (34, '點心選項 Choose Snacks', '薯條 (XL) French Fries (XL)'),
    (34, '飲品選擇 Choose Beverage', '冰紅茶【L｜甜度固定】Iced Black Tea(L)'),
    (34, '飲品選擇 Choose Beverage', '摩斯蒟蒻冰紅茶'),
    (34, '飲品選擇 Choose Beverage', '熱摩斯咖啡 【L】MOS Coffee(Hot)(L)'),
    (34, '飲品選擇 Choose Beverage', '冰摩斯咖啡 【L】MOS Coffee(Iced)(L)'),
    (34, '飲品選擇 Choose Beverage', '熱拿鐵咖啡 【L】Café Latte(Hot)(L)'),
    (34, '飲品選擇 Choose Beverage', '冰拿鐵咖啡 【L】Café Latte(Iced)(L)'),
    (34, '飲品選擇 Choose Beverage', '黃金地瓜冰奶茶【L |冰】Sweet Potato Milk Tea (Iced)(L)'),
    (34, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 熱】Sweet Potato Café Latte (Hot)(M)'),
    (34, '飲品選擇 Choose Beverage', '黃金地瓜拿鐵【M | 冰】Sweet Potato Café Latte (Iced)(M)'),
    (34, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【冰】Match Milk Tea(Iced)'),
    (34, '飲品選擇 Choose Beverage', '100%台灣冰綠茶【L|無糖】100% Taiwan Iced Green Tea(Sugar free)(L)'),
    (34, '飲品選擇 Choose Beverage', '冰紅茶【L|無糖】Iced Black Tea(Sugar free)(L)'),
    (34, '飲品選擇 Choose Beverage', '可樂【L】Coke(L)'),
    (34, '飲品選擇 Choose Beverage', '雪碧【L】Sprite(L)'),
    (34, '飲品選擇 Choose Beverage', '摩斯經典奶茶【L│冰】MOS Milk Tea (L) (Iced)'),
    (34, '飲品選擇 Choose Beverage', '柚子冰茶Pomelo Tea(Iced)'),
    (34, '飲品選擇 Choose Beverage', '100%新鮮橘子汁【M|不加冰】100% Orange Juice'),
    (34, '飲品選擇 Choose Beverage', '摩斯熱紅茶Hot Black Tea'),
    (34, '飲品選擇 Choose Beverage', '摩斯玄米煎茶MOS Genmai Green Tea'),
    (34, '飲品選擇 Choose Beverage', '豚汁蔬菜湯 Japanese Pork Soup'),
    (34, '飲品選擇 Choose Beverage', '玉米濃湯【L】Corn Soup (L)'),
    (34, '飲品選擇 Choose Beverage', '熱摩斯奶茶【M】MOS Milk Tea(Hot)'),
    (34, '飲品選擇 Choose Beverage', '摩斯抹茶歐蕾【熱】Match Milk Tea(Hot)'),
    (34, '點心加購 Add-Ons Snacks', '和風炸雞【1份】Mos Chicken'),
    (34, '點心加購 Add-Ons Snacks', 'MOS 米蕾夢【1 份】MOS Rice Lemon Cake'),
    (34, '點心加購 Add-Ons Snacks', '黃金夯地瓜 (L) Fried Sweet Potatoes'),
    (34, '點心加購 Add-Ons Snacks', '蝴蝶蝦薯餅組【1 份】Butterfly Shrimp Combo'),
    (34, '點心加購 Add-Ons Snacks', '摩斯雞塊【6個】(附酸甜醬 1 包)MOS Chicken Nuggets(6pcs)'),
    (34, '點心加購 Add-Ons Snacks', '辣味和風雞腿塊【3個】(小辣) Spicy Fried Chicken(3pcs) (Mild)'),
    (34, '點心加購 Add-Ons Snacks', '薯條 (XL) French Fries (XL)'),
    (34, '點心加購 Add-Ons Snacks', 'V型薯條【1份】V-Fries'),
    (42, '份量 / Size', '小 small'),
    (42, '份量 / Size', '大 Large'),
    (42, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (42, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (42, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (42, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (42, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (42, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (42, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (42, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (42, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (42, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (42, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (42, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (42, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (42, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (42, '飲料 / Drinks', '可口可樂 / Coke'),
    (42, '飲料 / Drinks', '可爾必思 / Calpis'),
    (42, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (43, '份量 / Size', '小 small'),
    (43, '份量 / Size', '大 Large'),
    (43, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (43, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (43, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (43, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (43, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (43, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (43, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (43, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (43, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (43, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (43, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (43, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (43, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (43, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (43, '飲料 / Drinks', '可口可樂 / Coke'),
    (43, '飲料 / Drinks', '可爾必思 / Calpis'),
    (43, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (44, '份量 / Size', '小 small'),
    (44, '份量 / Size', '大 Large'),
    (44, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (44, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (44, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (44, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (44, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (44, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (44, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (44, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (44, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (44, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (44, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (44, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (44, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (44, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (44, '飲料 / Drinks', '可口可樂 / Coke'),
    (44, '飲料 / Drinks', '可爾必思 / Calpis'),
    (44, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (45, '份量 / Size', '小 small'),
    (45, '份量 / Size', '大 Large'),
    (45, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (45, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (45, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (45, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (45, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (45, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (45, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (45, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (45, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (45, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (45, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (45, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (45, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (45, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (45, '飲料 / Drinks', '可口可樂 / Coke'),
    (45, '飲料 / Drinks', '可爾必思 / Calpis'),
    (45, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (46, '份量 / Size', '小 small'),
    (46, '份量 / Size', '大 Large'),
    (46, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (46, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (46, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (46, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (46, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (46, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (46, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (46, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (46, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (46, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (46, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (46, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (46, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (46, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (46, '飲料 / Drinks', '可口可樂 / Coke'),
    (46, '飲料 / Drinks', '可爾必思 / Calpis'),
    (46, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (47, '份量 / Size', '小 small'),
    (47, '份量 / Size', '大 Large'),
    (47, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (47, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (47, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (47, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (47, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (47, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (47, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (47, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (47, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (47, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (47, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (47, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (47, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (47, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (47, '飲料 / Drinks', '可口可樂 / Coke'),
    (47, '飲料 / Drinks', '可爾必思 / Calpis'),
    (47, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (48, '份量 / Size', '大 Large'),
    (48, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (48, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (48, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (48, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (48, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (48, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (48, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (48, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (48, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (48, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (48, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (48, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (48, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (48, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (48, '飲料 / Drinks', '可口可樂 / Coke'),
    (48, '飲料 / Drinks', '可爾必思 / Calpis'),
    (48, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (49, '份量 / Size', '小 small'),
    (49, '份量 / Size', '大 Large'),
    (49, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (49, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (49, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (49, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (49, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (49, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (49, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (49, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (49, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (49, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (49, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (49, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (49, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (49, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (49, '飲料 / Drinks', '可口可樂 / Coke'),
    (49, '飲料 / Drinks', '可爾必思 / Calpis'),
    (49, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (50, '份量 / Size', '小 small'),
    (50, '份量 / Size', '大 Large'),
    (50, '飯量 / Adjust the amount of rice', '飯少 / Less Steamed Rice'),
    (50, '飯量 / Adjust the amount of rice', '加飯 / Add Steamed Rice'),
    (50, '温泉蛋套餐 / Combo Meal（ $15 OFF!! ）', '温泉蛋 & 豬肉味噌湯 Soft Boiled Egg & Miso Soup'),
    (50, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★佐藤式豆芽菜 Signature Bean Sprouts'),
    (50, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '日式涼拌菜 / Japanese Cold Vegetable'),
    (50, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '韓國泡菜 / Korean Kimchi'),
    (50, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '★豬肉味噌湯 / Pork Miso Soup'),
    (50, '優惠加購配菜 / Side Order（ $5 OFF!! ）', '納豆 Natto'),
    (50, '配料 / Toppings', '★溫泉蛋 / Soft Boiled Egg'),
    (50, '配料 / Toppings', '蔥花 Chopped Green Onion'),
    (50, '配料 / Toppings', '福神漬 Fukujinzuke'),
    (50, '配料 / Toppings', '紅薑絲 Red Ginger'),
    (50, '配料 / Toppings', '日式一味辣粉 Chili Powder'),
    (50, '配料 / Toppings', '另加一份麥飯 Wheat Rice（200g）'),
    (50, '飲料 / Drinks', '可口可樂 / Coke'),
    (50, '飲料 / Drinks', '可爾必思 / Calpis'),
    (50, '飲料 / Drinks', '100%柳橙汁 / Orange Juice'),
    (62, '份量', '加大'),
    (63, '份量', '加大'),
    (72, '加購選項', '半顆水煮蛋'),
    (72, '加購選項', '楽坡地瓜泥(一球)'),
    (72, '加購選項', '黑金黎飯加量'),
    (72, '加購選項', '杏鮑菇'),
    (72, '加購選項', '椒鹽梅花豬'),
    (72, '加購選項', '威力雞胸'),
    (73, '加購選項', '半顆水煮蛋'),
    (73, '加購選項', '楽坡地瓜泥(一球)'),
    (73, '加購選項', '黑金黎飯加量'),
    (73, '加購選項', '杏鮑菇'),
    (73, '加購選項', '椒鹽梅花豬'),
    (73, '加購選項', '威力雞胸'),
    (74, '加購選項', '半顆水煮蛋'),
    (74, '加購選項', '楽坡地瓜泥(一球)'),
    (74, '加購選項', '黑金黎飯加量'),
    (74, '加購選項', '杏鮑菇'),
    (74, '加購選項', '椒鹽梅花豬'),
    (74, '加購選項', '威力雞胸'),
    (75, '加購選項', '半顆水煮蛋'),
    (75, '加購選項', '楽坡地瓜泥(一球)'),
    (75, '加購選項', '黑金黎飯加量'),
    (75, '加購選項', '杏鮑菇'),
    (75, '加購選項', '椒鹽梅花豬'),
    (75, '加購選項', '威力雞胸'),
    (76, '加購選項', '半顆水煮蛋'),
    (76, '加購選項', '楽坡地瓜泥(一球)'),
    (76, '加購選項', '黑金黎飯加量'),
    (76, '加購選項', '杏鮑菇'),
    (76, '加購選項', '椒鹽梅花豬'),
    (76, '加購選項', '威力雞胸'),
    (77, '加購選項', '半顆水煮蛋'),
    (77, '加購選項', '楽坡地瓜泥(一球)'),
    (77, '加購選項', '黑金黎飯加量'),
    (77, '加購選項', '杏鮑菇'),
    (77, '加購選項', '椒鹽梅花豬'),
    (77, '加購選項', '威力雞胸'),
    (78, '加購選項', '半顆水煮蛋'),
    (78, '加購選項', '楽坡地瓜泥(一球)'),
    (78, '加購選項', '黑金黎飯加量'),
    (78, '加購選項', '杏鮑菇'),
    (78, '加購選項', '椒鹽梅花豬'),
    (78, '加購選項', '威力雞胸'),
    (79, '飯量選擇', '飯減量（130克）'),
    (79, '飯量選擇', '飯量普通（200克）'),
    (79, '飯量選擇', '飯加量（300克）'),
    (79, '飯量選擇', '飯加量(300克) 丼飯醬汁增量'),
    (79, '配料選擇', '配料全加'),
    (79, '配料選擇', '加福神漬'),
    (79, '配料選擇', '加紅薑絲'),
    (79, '配料選擇', '加蘿蔔泥'),
    (79, '配料選擇', '加蔥花'),
    (79, '配料選擇', '不附湯'),
    (80, '飯量選擇', '飯減量（130克）'),
    (80, '飯量選擇', '飯量普通（200克）'),
    (80, '飯量選擇', '飯加量（300克）'),
    (80, '飯量選擇', '飯加量(300克) 丼飯醬汁增量'),
    (80, '配料選擇', '配料全加'),
    (80, '配料選擇', '加福神漬'),
    (80, '配料選擇', '加紅薑絲'),
    (80, '配料選擇', '加蘿蔔泥'),
    (80, '配料選擇', '加蔥花'),
    (80, '配料選擇', '不附湯'),
    (81, '飯量選擇', '飯減量（130克）'),
    (81, '飯量選擇', '飯量普通（200克）'),
    (81, '飯量選擇', '飯加量（300克）'),
    (81, '飯量選擇', '飯加量(300克) 丼飯醬汁增量'),
    (81, '配料選擇', '配料全加'),
    (81, '配料選擇', '加福神漬'),
    (81, '配料選擇', '加紅薑絲'),
    (81, '配料選擇', '加蘿蔔泥'),
    (81, '配料選擇', '加蔥花'),
    (81, '配料選擇', '不附湯'),
    (82, '飯量選擇', '飯減量（130克）'),
    (82, '飯量選擇', '飯量普通（200克）'),
    (82, '飯量選擇', '飯加量（300克）'),
    (82, '飯量選擇', '飯加量(300克) 丼飯醬汁增量'),
    (82, '配料選擇', '配料全加'),
    (82, '配料選擇', '加福神漬'),
    (82, '配料選擇', '加紅薑絲'),
    (82, '配料選擇', '加蘿蔔泥'),
    (82, '配料選擇', '加蔥花'),
    (82, '配料選擇', '不附湯'),
    (83, '飯量選擇', '飯減量（130克）'),
    (83, '飯量選擇', '飯量普通（200克）'),
    (83, '飯量選擇', '飯加量（300克）'),
    (83, '飯量選擇', '飯加量(300克) 丼飯醬汁增量'),
    (83, '配料選擇', '配料全加'),
    (83, '配料選擇', '加福神漬'),
    (83, '配料選擇', '加紅薑絲'),
    (83, '配料選擇', '加蘿蔔泥'),
    (83, '配料選擇', '加蔥花'),
    (83, '配料選擇', '不附湯'),
    (84, '甜度選擇 Choose Sweetness Level', '正常糖 Regular Sugar'),
    (84, '甜度選擇 Choose Sweetness Level', '7 分糖 70% Sugar'),
    (84, '甜度選擇 Choose Sweetness Level', '5 分糖 50% Sugar'),
    (84, '甜度選擇 Choose Sweetness Level', '3 分糖 30% Sugar'),
    (84, '甜度選擇 Choose Sweetness Level', '1 分糖 10% Sugar'),
    (84, '甜度選擇 Choose Sweetness Level', '無糖 Sugar-Free'),
    (84, '冰量選擇 Ice Level', '正常冰 Regular Ice'),
    (84, '冰量選擇 Ice Level', '7 分冰 70% Ice'),
    (84, '冰量選擇 Ice Level', '3 分冰 30% Ice'),
    (84, '冰量選擇 Ice Level', '去冰 Ice-Free'),
    (84, '加料 Add-On', '綠茶凍 Green Tea Jelly'),
    (84, '加料 Add-On', '椰果 Coconut Jelly'),
    (84, '加料 Add-On', '寒天晶球 Agar Tapioca'),
    (85, '甜度選擇 Choose Sweetness Level', '正常糖 Regular Sugar'),
    (85, '甜度選擇 Choose Sweetness Level', '7 分糖 70% Sugar'),
    (85, '甜度選擇 Choose Sweetness Level', '5 分糖 50% Sugar'),
    (85, '甜度選擇 Choose Sweetness Level', '3 分糖 30% Sugar'),
    (85, '甜度選擇 Choose Sweetness Level', '1 分糖 10% Sugar'),
    (85, '甜度選擇 Choose Sweetness Level', '無糖 Sugar-Free'),
    (85, '冰量選擇 Ice Level', '正常冰 Regular Ice'),
    (85, '冰量選擇 Ice Level', '7 分冰 70% Ice'),
    (85, '冰量選擇 Ice Level', '3 分冰 30% Ice'),
    (85, '冰量選擇 Ice Level', '去冰 Ice-Free'),
    (85, '加料 Add-On', '綠茶凍 Green Tea Jelly'),
    (85, '加料 Add-On', '椰果 Coconut Jelly'),
    (85, '加料 Add-On', '寒天晶球 Agar Tapioca'),
    (86, '甜度選擇 Choose Sweetness Level', '正常糖 Regular Sugar'),
    (86, '甜度選擇 Choose Sweetness Level', '7 分糖 70% Sugar'),
    (86, '甜度選擇 Choose Sweetness Level', '5 分糖 50% Sugar'),
    (86, '甜度選擇 Choose Sweetness Level', '3 分糖 30% Sugar'),
    (86, '甜度選擇 Choose Sweetness Level', '1 分糖 10% Sugar'),
    (86, '甜度選擇 Choose Sweetness Level', '無糖 Sugar-Free'),
    (86, '冰量選擇 Ice Level', '正常冰 Regular Ice'),
    (86, '冰量選擇 Ice Level', '7 分冰 70% Ice'),
    (86, '冰量選擇 Ice Level', '3 分冰 30% Ice'),
    (86, '冰量選擇 Ice Level', '去冰 Ice-Free'),
    (86, '溫度 Beverage Temperature', '冰 (中杯) Ice (Medium)'),
    (86, '溫度 Beverage Temperature', '冰 (大杯) Ice (Large)'),
    (86, '溫度 Beverage Temperature', '熱 (中杯) Hot (Medium)'),
    (87, '甜度選擇 Choose Sweetness Level', '正常糖 Regular Sugar'),
    (87, '甜度選擇 Choose Sweetness Level', '7 分糖 70% Sugar'),
    (87, '甜度選擇 Choose Sweetness Level', '5 分糖 50% Sugar'),
    (87, '甜度選擇 Choose Sweetness Level', '3 分糖 30% Sugar'),
    (87, '甜度選擇 Choose Sweetness Level', '1 分糖 10% Sugar'),
    (87, '甜度選擇 Choose Sweetness Level', '無糖 Sugar-Free'),
    (87, '冰量選擇 Ice Level', '正常冰 Regular Ice'),
    (87, '冰量選擇 Ice Level', '7 分冰 70% Ice'),
    (87, '冰量選擇 Ice Level', '3 分冰 30% Ice'),
    (87, '冰量選擇 Ice Level', '去冰 Ice-Free'),
    (87, '加料 Add-On', '綠茶凍 Green Tea Jelly'),
    (87, '加料 Add-On', '椰果 Coconut Jelly'),
    (87, '加料 Add-On', '寒天晶球 Agar Tapioca'),
    (88, '甜度選擇 Choose Sweetness Level', '正常糖 Regular Sugar'),
    (88, '甜度選擇 Choose Sweetness Level', '7 分糖 70% Sugar'),
    (88, '甜度選擇 Choose Sweetness Level', '5 分糖 50% Sugar'),
    (88, '甜度選擇 Choose Sweetness Level', '3 分糖 30% Sugar'),
    (88, '甜度選擇 Choose Sweetness Level', '1 分糖 10% Sugar'),
    (88, '甜度選擇 Choose Sweetness Level', '無糖 Sugar-Free'),
    (88, '冰量選擇 Ice Level', '正常冰 Regular Ice'),
    (88, '冰量選擇 Ice Level', '7 分冰 70% Ice'),
    (88, '冰量選擇 Ice Level', '3 分冰 30% Ice'),
    (88, '冰量選擇 Ice Level', '去冰 Ice-Free'),
    (88, '加料 Add-On', '綠茶凍 Green Tea Jelly'),
    (88, '加料 Add-On', '椰果 Coconut Jelly'),
    (88, '加料 Add-On', '寒天晶球 Agar Tapioca'),
    (89, '甜度選擇 Choose Sweetness Level', '正常糖 Regular Sugar'),
    (89, '甜度選擇 Choose Sweetness Level', '7 分糖 70% Sugar'),
    (89, '甜度選擇 Choose Sweetness Level', '5 分糖 50% Sugar'),
    (89, '甜度選擇 Choose Sweetness Level', '3 分糖 30% Sugar'),
    (89, '甜度選擇 Choose Sweetness Level', '1 分糖 10% Sugar'),
    (89, '甜度選擇 Choose Sweetness Level', '無糖 Sugar-Free'),
    (89, '冰量選擇 Ice Level', '正常冰 Regular Ice'),
    (89, '冰量選擇 Ice Level', '7 分冰 70% Ice'),
    (89, '冰量選擇 Ice Level', '3 分冰 30% Ice'),
    (89, '冰量選擇 Ice Level', '去冰 Ice-Free'),
    (89, '加料 Add-On', '綠茶凍 Green Tea Jelly'),
    (89, '加料 Add-On', '椰果 Coconut Jelly'),
    (89, '加料 Add-On', '寒天晶球 Agar Tapioca')





