/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Price int64 `json:"price"`

	ShippingDiscountBool bool `json:"shipping_discount_bool"`

	SeasoningDiscountBool bool `json:"seasoning_discount_bool"`
}
