/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TimePeriod struct {

	StartDate string `json:"start_date,omitempty"`

	EndDate string `json:"end_date,omitempty"`
}
