/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type OneStoreListInfo struct {
	StoreId float64 `json:"store_id"`

	Name string `json:"name"`

	Rate float32 `json:"rate"`

	Picture string `json:"picture"`

	CategoryArray []Category `json:"category_array"`
}
