/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserDataShort struct {
	UserId int64 `json:"user_id"`

	UserName string `json:"user_name"`

	UserEmail string `json:"user_email"`

	Authority int64 `json:"authority"`

	Status int64 `json:"status"`
}
