/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CartInfo struct {
	CustomerID int `json:"customer_id"`

	ProductID int `json:"product_id"`

	StoreID int `json:"store_id"`

	ProductQuantity int `json:"product_quantity"`
}
