/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductInfo struct {

	ProductId int64 `json:"productId"`

	Name string `json:"name"`

	CatogoryId int64 `json:"catogoryId"`

	Description string `json:"description"`

	Price int64 `json:"price"`

	Storage int64 `json:"storage"`
}
