/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProductStatistic struct {

	ProductId int64 `json:"product_id"`

	ProductName string `json:"product_name"`

	ProductQuantity int64 `json:"product_quantity"`

	TotalPrice int64 `json:"total_price"`
}
