/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutInfo struct {

	SeasoningDiscountId int64 `json:"seasoning_discount_id"`

	ShippingDiscountId int64 `json:"shipping_discount_id"`

	TakingMethod int64 `json:"taking_method"`
}
