/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DiscountInfo struct {
	DiscountId int64 `json:"discount_id"`

	DiscountType int64 `json:"discount_type"`

	Status int64 `json:"status"`
}
