/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StoreInfo struct {
	Id string `json:"id"`

	Name string `json:"name"`

	Address string `json:"address"`

	Email string `json:"email"`

	Phone string `json:"phone,omitempty"`
}
