/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HistoryInfo struct {
	CustomerId int64 `json:"customer_id"`

	CartId int64 `json:"cart_id"`

	StoreId int64 `json:"store_id"`

	OrderDate string `json:"order_date"`

	TotalPrice int64 `json:"total_price"`

	StoreName string `json:"store_name"`

	StoreRate float32 `json:"store_rate"`

	StorePicture string `json:"store_picture"`

	Status int64 `json:"status"`

	Rate int64 `json:"rate"`
}
