/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RecommendInfo struct {
	StoreId float64 `json:"store_id"`

	ProductId float64 `json:"product_id"`

	Picture string `json:"picture"`

	ProductName string `json:"product_name"`
}
