/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShippingDiscount struct {
	DiscountId int64 `json:"discount_id"`

	DiscountName string `json:"discount_name"`

	DiscountDescription string `json:"discount_description"`

	DiscountMaxPrice int64 `json:"discount_max_price"`

	Status int `json:"status"`
}
