/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Category struct {

	CategoryId int64 `json:"category_id,omitempty"`

	CategoryName string `json:"category_name,omitempty"`
}
