/*
 * PUN street Universal Access - OpenAPI 3.0
 *
 * pua
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CartInfo struct {
	CustomerID string `json:"customer_id"`

	ProductID string `json:"product_id"`

	StoreID string `json:"store_id"`

	ProductQuantity string `json:"product_quantity"`
}
