// place files you want to import through the `$lib` alias in this folder.
import BlueButton from './components/PUA/blueButton.svelte';
export { BlueButton };
import Counter from './components/PUA/counter.svelte';
export { Counter };
import ProductCard from './components/PUA/productCard.svelte';
export { ProductCard };
import CartItemCard from './components/PUA/cartItemCard.svelte';
export { CartItemCard };
import Label from './components/PUA/Label.svelte';
export { Label as PUALabel };
import CartLabelBox from './components/PUA/cartLabelBox.svelte';
export { CartLabelBox };
import ShippingCoupon from './components/PUA/shippingCoupon.svelte';
export { ShippingCoupon };
import DenyButton from './components/PUA/denyButton.svelte';
export { DenyButton };
import OkButton from './components/PUA/OkButton.svelte';
export { OkButton };
import SeasoningCoupon from './components/PUA/seasoningCoupon.svelte';
export { SeasoningCoupon };
import CartMoreItemCard from './components/PUA/cartMoreItemCard.svelte';
export { CartMoreItemCard };
import BuyNforOneFree from './components/PUA/buyNforMFree.svelte';
export { BuyNforOneFree };
import HistoryCard from './components/PUA/historyCard.svelte';
export { HistoryCard };
import CheckOrderPart from './components/PUA/checkOrderPart.svelte';
export { CheckOrderPart };
import ProgressBar from './components/PUA/progressBar.svelte';
export { ProgressBar };
import Redradiobox from './components/PUA/redRadioBox.svelte';
export { Redradiobox };
import Textcontainer from './components/PUA/textContainer.svelte';
export { Textcontainer };
import Textarea from '$lib/components/PUA/textareaContainer.svelte';
export { Textarea };
import DisCountArea from './components/PUA/discountArea.svelte';
export { DisCountArea };
import StatusButton from './components/PUA/statusButton.svelte';
export { StatusButton };
import ErrorMsg from './components/PUA/errorMsg.svelte';
export { ErrorMsg };
import NeedChooseLabel from './components/PUA/needChooseLabel.svelte';
export { NeedChooseLabel };
import DiscountArea from './components/PUA/discountArea.svelte';
export { DiscountArea };
import Checkcontainer from '$lib/components/PUA/checkcontainer.svelte';
export { Checkcontainer };
import InputBox from './components/PUA/InputBox.svelte';
export { InputBox };
import CheckBox from './components/PUA/CheckBox.svelte';
export { CheckBox };
import SortTag from './components/PUA/sortTag.svelte';
export { SortTag };
import DualRangeSlider from './components/PUA/dualRangeSlider.svelte';
export { DualRangeSlider };

export type category = { category_name: string; category_id: number };

export type shopListResponse = {
	address: string;
	description: string;
	name: string;
	picture: string;
	rate: number;
	rate_count: number;
	shipping_fee: number;
	status: number;
	store_id: number;
	category_array: category[];
};
import CategoryLabel from '$lib/components/PUA/store_page_seller/categoryLabel.svelte';
export { CategoryLabel };
import DiscountCard from '$lib/components/PUA/store_page_seller/discountCard.svelte';
export { DiscountCard };
import StoreProductCard from '$lib/components/PUA/store_page_seller/storeProductCard.svelte';
export { StoreProductCard };
import ErrorMessage from './components/PUA/ErrorMessage.svelte';
export { ErrorMessage };

export type product_order = {
	event_discount_max_quantity: number;
	event_discount_id: number;
	product_id: number;
	product_price: number;
	product_name: string;
	product_quantity: number;
	product_picture: string;
};
export type shipping_discount = {
	discount_name: string;
	discount_description: string;
	discount_max_price: number;
	discount_id: number;
	status: number;
};
export type seasoning_discount = {
	discount_start_date: string;
	discount_name: string;
	discount_end_date: string;
	discount_description: string;
	discount_percentage: number;
	discount_id: number;
	status: number;
};
export type storeOrderInfo = {
	store_id: 1;
	store_name: string;
	store_shipping_fee: number;
	product_order: product_order[];
	shipping_discount: shipping_discount;
	shipping_discount_bool: true;
	seasoning_discount: seasoning_discount;
	seasoning_discount_bool: true;
	total_price: number;
};
export type cartInfo = {
	real_total_price: number;
	store_order_info_array: storeOrderInfo[];
};
import Order from './components/PUA/order.svelte';
export { Order };
